-- Seed: Beatles, Red Hot Chili Peppers and Classic Rock songs for English learning
insert into feed_items (id, type, title, channel, artist, youtube_id, duration, level, tags, preview) values
  ('music-let-it-be', 'music', 'Let It Be', null, 'The Beatles', 'CGj85pVzRJs', '3:52', 'A2', array['classic rock','ballad','simple vocabulary','hope'], 'Paul McCartney''s timeless ballad with slow, clear pronunciation and simple, comforting vocabulary. Perfect for A2 learners to practice listening comprehension and present tense expressions.'),
  ('music-hey-jude', 'music', 'Hey Jude', null, 'The Beatles', 'A_MjCqQoLLA', '7:11', 'A2', array['classic rock','chorus','phrasal verbs','encouragement'], 'One of the most iconic choruses in rock history. Simple and repetitive structure with common phrasal verbs like ''take a sad song'' and ''make it better'' — great for A2 learners building vocabulary through repetition.'),
  ('music-yesterday', 'music', 'Yesterday', null, 'The Beatles', '2eAhqbmXfqU', '2:05', 'B1', array['ballad','past tense','grammar','emotions'], 'Short and slow, rich in past tense and conditional structures. A grammar gem for B1 learners — packed with past simple and used-to patterns in an unforgettable melody.'),
  ('music-come-together', 'music', 'Come Together', null, 'The Beatles', '45cYwDMibGo', '4:19', 'B2', array['classic rock','abstract','rhythm','figurative language'], 'John Lennon''s hypnotic lyrics are full of abstract imagery and unusual expressions. A B2 challenge that exposes learners to creative, non-literal English and the rhythm of native speech.'),
  ('music-in-my-life', 'music', 'In My Life', null, 'The Beatles', 'QR1CwJTXUIk', '2:26', 'B1', array['classic rock','nostalgia','past tense','comparative'], 'A reflective song about memory and love, rich in past tense and comparative structures. Lennon''s clear diction and poetic simplicity make this perfect for intermediate learners.'),
  ('music-under-the-bridge', 'music', 'Under the Bridge', null, 'Red Hot Chili Peppers', 'GLvohMXgcBo', '4:24', 'B1', array['rock','storytelling','emotions','phrasal verbs'], 'Kiedis narrates a personal story with vivid imagery and emotional depth. Slow verses and clear enunciation help learners follow complex storytelling in English at a comfortable pace.'),
  ('music-californication', 'music', 'Californication', null, 'Red Hot Chili Peppers', 'YlUKcNNmywk', '5:21', 'B2', array['rock','American culture','advanced vocabulary','figurative language'], 'A critique of Hollywood culture packed with cultural references and advanced vocabulary. Challenging and rewarding for B2 learners interested in American idioms and figurative language.'),
  ('music-scar-tissue', 'music', 'Scar Tissue', null, 'Red Hot Chili Peppers', 'mzJj5-lubeM', '3:37', 'B1', array['rock','metaphors','imagery','emotional'], 'Slow, melodic, and full of vivid metaphors. The measured pace and poetic imagery make it excellent for intermediate learners studying figurative language and emotional expression.'),
  ('music-otherside', 'music', 'Otherside', null, 'Red Hot Chili Peppers', 'rn_YodiJO6k', '4:15', 'B1', array['rock','emotional vocabulary','imagery','storytelling'], 'A haunting song about struggle and recovery. The measured pace and emotional vocabulary make it accessible for B1 learners wanting to explore deeper English expression through music.'),
  ('music-sweet-child-o-mine', 'music', 'Sweet Child O'' Mine', null, 'Guns N'' Roses', '1w7OgIMMRc4', '5:55', 'B1', array['rock','80s','romantic','descriptive vocabulary'], 'Axl Rose''s iconic rock ballad paints a vivid portrait with descriptive vocabulary and a clear verse-chorus structure. The emotional delivery and consistent rhyme scheme help B1 learners build listening stamina.'),
  ('music-hotel-california', 'music', 'Hotel California', null, 'Eagles', 'dLl4PZtxia8', '6:30', 'B2', array['classic rock','metaphor','storytelling','American culture'], 'One of rock''s greatest narratives — layered in allegory and symbolism. Rich vocabulary, complex sentence structures and cultural references to American excess make this a compelling B2 challenge.')
on conflict (id) do nothing;
